### ISSUE TITLE
Maxthon Browser

### ISSUE THREAD

**Issue by Hipstir** [perceptron8/pinky.ext#20]
Hi
The screenshot of Pinky in action looks great.
 Is there any chance of adding Pinky to Maxthon Browser.

**Comment by perceptron8** [comment]
Hi! Currently there's no chance, as Pinky requires WebExtensions API and Maxthon provides it's own SDK.

**Comment by Hipstir** [comment]
:-{   Thanks for looking.
What about Microsoft Edge then. The Windows 10 Explorer

**Comment by perceptron8** [comment]
Are Web Extensions already supported in Microsoft Edge? Some time ago they were only available in Windows 10 Insider Preview.

**Comment by perceptron8** [comment]
https://docs.microsoft.com/en-us/microsoft-edge/extensions/api-support/extension-api-roadmap#publicly-available-builds

Looks like they are...

**Comment by perceptron8** [comment]
I have found one "minor" incompatibility:

> Network requests from `<object>` and `<embed>` elements are not supported.
(https://docs.microsoft.com/en-us/microsoft-edge/extensions/api-support/supported-apis#webrequest)

Unfortunately, this means I'm stuck. Is anyone suprised?

BTW, I couldn't get [Microsoft Edge Extension Toolkit](https://www.microsoft.com/pl-pl/store/p/microsoft-edge-extension-toolkit/9nblggh4txvb) to work - usage of which would be helpful as Microsoft decided to use  `browser.*` instead of `chrome.*` namespace, 10 or 20 instead of 48-px icons, require some non-required manifest entries and so on, just to make developers life a little bit more miserable.

I will check again within a 6 month or so.

**Comment by Hipstir** [comment]
Cheers. Sorry for the bother
