### ISSUE TITLE
hide Pinky

### ISSUE THREAD

**Issue by Sanja21** [perceptron8/pinky.ext#22]
Hello,

is there a way to implement a "Hide function" for pinky?
I mean to disable pinky with a click and the possibility to enable it.
For now i have to uninstall pinky to see the normal graphics and install it again, if i need the help.

I hope you get what i wanted to describe ^^
Thanks in advance!

**Comment by perceptron8** [comment]
Hi!

You can disable Pinky with a click without uninstalling it already. Please, check [Install and manage extensions](https://support.google.com/chrome_webstore/answer/2664769?hl=en) for "Turn extensions on or off".

Dynamic graphics switching could be problematic as 307 redirections can be cached. Pinky can't clear cache, because it has no permissions (by design). It's possible to prevent caching, but I don't want to play with headers as different browsers may behave differently - this function would be fragile and error-prone.

I'm not sure if just disabling Pinky will do the job, but you can try. Something that will work for sure is disabling, then clearing cache.

**Comment by perceptron8** [comment]
I focused on something that could be done, but wouldn't be worth doing. You probably asked about even more dynamic collections switching - some kind of toggle allowing to change graphics without game reloading - am I right? If so, then - unfortunately - it's impossible at all. TSO game engine loads and caches images internally, at least as long as you stay on one island. I hope that this explains a little bit more than my previous answer.

**Comment by Sanja21** [comment]
Hi, 

now I understand why a dynamic switching is not possible.
But the solution with the extensions manager would work for me.

Thanks for your answers :)
