### ISSUE TITLE
q: pinky showing nothing on ff esr 52.7.x esr x64

### ISSUE THREAD

**Issue by pinkyuser** [perceptron8/pinky.ext#38]
tyvm for this great tool! 

prolly config issue on my end, which I can't resolve. takes away tso collies, but does not replace them with pinky square.

Multiprocess Windows 	5/5 (Enabled by default)

MozillaFirefox-52.7.3-86.1.x86_64 (ESR)

Linux linux-v68e 4.11.8-2-default #1 SMP PREEMPT ... x86_64 x86_64 x86_64 GNU/Linu

**Comment by perceptron8** [comment]
have you tried clearing cache?

**Comment by pinkyuser** [comment]
installed - cleared cache - restarted - cleared cache again - no change

**Comment by perceptron8** [comment]
more like herbs or fire?

https://ubistatic-a.akamaihd.net/0018/live/GFX_HASHED/building_lib/bd76cd8196c23aaf73139bc263002cf759afc1ce.png

herbs: we have a problem
fire: pinky works correctly

**Comment by perceptron8** [comment]
could you provide a screenshot? please include address bar

**Comment by pinkyuser** [comment]
thanks! ok, will do after respawn

**Comment by pinkyuser** [comment]
uploaded screenshot

**Comment by perceptron8** [comment]
Yeah, thanks, but please open and make a screenshot of https://ubistatic-a.akamaihd.net/0018/live/GFX_HASHED/building_lib/bd76cd8196c23aaf73139bc263002cf759afc1ce.png instead...

**Comment by perceptron8** [comment]
You can also just tell me if you are redirected or not (if pinky is working, you will end at https://ubistatic-a.akamaihd.net/0018/live/GFX_HASHED/building_lib/f9f7e2bacd84c76001820a3621bda5c6959d609d.png).

**Comment by pinkyuser** [comment]
![pinky2](https://user-images.githubusercontent.com/38095077/38374655-81d163dc-38f4-11e8-9730-2cb8efb54af3.png)

**Comment by perceptron8** [comment]
To summarize: it seems that pinky is fine, because https://ubistatic-a.akamaihd.net/0018/live/GFX_HASHED/building_lib/bd76cd8196c23aaf73139bc263002cf759afc1ce.png is being redirected to https://ubistatic-a.akamaihd.net/0018/live/GFX_HASHED/building_lib/f9f7e2bacd84c76001820a3621bda5c6959d609d.png.

Will try something else... Has it worked before? 52.6.x maybe?

**Comment by pinkyuser** [comment]
did work before, but not sure which versions - likely in 45.x esr tree.

[as well I believe it works in quantum (non esr) tree, but there's a completely different regression:
https://bugzilla.mozilla.org/show_bug.cgi?id=1417243

**Comment by perceptron8** [comment]
I could review up to ~100 commits at https://hg.mozilla.org/releases/mozilla-esr52/log/FIREFOX_52_7_3esr_RELEASE, but checking everything since 45.x is way too much.

Would you like to test some earlier 52 esr versions?

**Comment by pinkyuser** [comment]
can try an package which easily installs into suse leap 42

**Comment by perceptron8** [comment]
https://hg.mozilla.org/releases/mozilla-esr52/shortlog/FIREFOX_52_6_0esr_RELEASE

Time to start digging! I'll let you know when I find sth.

**Comment by perceptron8** [comment]
Oh, this was a waste of time. I just used fresh VM with openSUSE Leap 42.3 + Firefox 52.7.3 and Pinky works like a charm.

#### cat /etc/os-release

> NAME="openSUSE Leap"
> VERSION="42.3"
> ID=opensuse
> ID_LIKE="suse"
> VERSION_ID="42.3"
> PRETTY_NAME="openSUSE Leap 42.3"
> ANSI_COLOR="0;32"
> CPE_NAME="cpe:/o:opensuse:leap:42.3"
> BUG_REPORT_URL="https://bugs.opensuse.org"
> HOME_URL="https://www.opensuse.org/"

#### firefox about:support
> Name: Firefox
> Version: 52.7.3
> Build ID: 20180322140748
> User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0
> OS: Linux 4.4.76-1-default
> Multiprocess Windows: 1/1 (Enabled by user)
> Safe Mode: false

---

Follow https://wiki.mozilla.org/Electrolysis#Force_Enable to make sure that e10s is enabled. It's possible that "enabled by user" instead of "enabled by default" may be needed (?). Check if forcing e10s helped. Remember to clear cache first.

Still nothing? Problem may be caused by some other add-ons / plugins that interfere with Pinky. You may like to [create new firefox profile](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles#w_creating-a-profile) and use it for testing.

**Comment by pinkyuser** [comment]
many thanks for the time invested - but sorry to have wasted your time :( 

playing around with about:config
browser.tabs.remote.autostart to true
seems to do the trick (at least on friends island for the time being) -
not sure how it is related though

**Comment by pinkyuser** [comment]
many thanks for the time invested - but sorry to have wasted your time :( 

playing around with about:config
browser.tabs.remote.autostart to true
seems to do the trick (at least on friends island for the time being) -
not sure how it is related though

**Comment by perceptron8** [comment]
Don't be sorry! I meant digging into shortlog, nothing else. I'm glad that I could help - and happy that collectibles are pink again :)
