### ISSUE TITLE
Pinky for Puffin Web Browser

### ISSUE THREAD

**Issue by domi2000** [perceptron8/pinky.ext#43]
It would be nice if you can add extension to Puffin Web Browser so we can have pinky on mobile phones.

Thank you, great work!

**Comment by perceptron8** [comment]
Does Puffin support extensions at all? I truly doubt...

Here's how documentation looks if there is such support:
- https://developer.chrome.com/extensions
- https://developer.mozilla.org/en-US/Add-ons/WebExtensions
- https://dev.opera.com/extensions/
- https://docs.microsoft.com/en-us/microsoft-edge/extensions

Chrome, Firefox and Opera supports all what's needed for Pinky to work.

In Edge, Network requests from `<object>` and `<embed>` elements are not supported. That's why there's no Pinky for Edge (see [webRequest](https://docs.microsoft.com/en-us/microsoft-edge/extensions/api-support/supported-apis#webrequest) -> Chrome incompatibilities).

It seems that there's nothing I can do about Puffin.

**Comment by domi2000** [comment]
Thank you!

**Comment by perceptron8** [comment]
You're welcome! Thanks for asking! :)
