### ISSUE TITLE
pinky not working in opera after recent update in settlers

### ISSUE THREAD

**Issue by shandaow** [perceptron8/pinky.ext#66]
iv closed and reinstalled and still not working, cleared cache, any update i can do? pinky is most helpful

**Comment by horacis** [comment]
also not working in firefox 69.0.3

**Comment by perceptron8** [comment]
@horacis see https://github.com/perceptron8/pinky.ext/issues/65

**Comment by perceptron8** [comment]
@shandaow see https://github.com/perceptron8/pinky.ext/issues/64#issuecomment-542380481

**Comment by horacis** [comment]
thank you :) working fine

**Comment by perceptron8** [comment]
Pinky v0.4.8 is awaiting moderation. It needs to be manually reviewed and moderated before it can be added to Opera Stable. It is currently available for download in Opera Developer and Opera Beta. 

v0.4.8 was submitted few days ago (Oct 15, 2019), but I'm still waiting for v0.4.7 (since Oct 9, 2019) and v0.4.6 (since Sep 3, 2019) to be reviewed.

I strongly recommend all Opera users to get [Install Chrome Extensions](https://addons.opera.com/pl/extensions/details/install-chrome-extensions/) and [install Pinky directly from Chrome Web Store](https://chrome.google.com/webstore/detail/pinky/eijmklfnehnnkbfcoabieogaomookbna)).

**Comment by perceptron8** [comment]
Pinky has been finally reviewed, moderated and published. Some pinging was necessary though.

> Status has changed for Pinky
> 
> Pinky v0.4.8 on Opera Current:
> Published.
