### ISSUE TITLE
Pinky in the transitional client "The Settlers Online RC1"?

### ISSUE THREAD

**Issue by janrenzlow** [perceptron8/pinky.ext#72]
Hello Michal, 
thesettleronline offers a transition client that can be downloaded from https://static3.cdn.ubi.com/TSO/The Settlers Online Installer RC1.exe. The client currently only works on TSO test servers. It's a minimal browser that - as far as I can tell - doesn't allow any extensions. Is there still a chance to add Pinky in this client?
Thank you very much for your answer and your effort
Jan

Witaj Michal, 
thesettleronline oferuje klienta przejściowego, który można pobrać z https://static3.cdn.ubi.com/TSO/The Settlers Online Installer RC1.exe. Klient obecnie działa tylko na serwerach testowych OSP. To minimalna przeglądarka, która - o ile wiem - nie pozwala na żadne rozszerzenia. Czy nadal jest szansa, aby dodać Pinky do tego klienta? 
Bardzo dziękuję za odpowiedź i wysiłek
Jan

https://i.imgur.com/XNYUQD7.jpg

**Comment by perceptron8** [comment]
Hello, Jan,

it seems that this client is not even a browser. It looks more like an Adobe AIR + Adobe Flash based app. I don't think it is or will be possible to add Pinky to this client. I'll verify that from time to time in case something changes.

Best wishes
Michal

**Comment by janrenzlow** [comment]
BB published the new client "The Settlers Online Installer RC2", but still an Adobe AIR + Adobe Flash + Harman based app

**Comment by Algernoon123** [comment]
Hi, is there an way to use tools like wireshark or Scapy to change the traffic data of the images ?

**Comment by Paskal-MY** [comment]
The new TSO client is preventing the use of this useful extension. I hope there will be some solution for this.

Thanks for your previous and upcoming hard work :)

**Comment by perceptron8** [comment]
@Algernoon123 You may try to experiment with proxy servers.
@Paskal-MY I hope that this new client is interim indeed.

**Comment by Kshyhoo67** [comment]
Witam.Nie wiem, czy nie złamię regulaminu, pisząc w ojczystym języku, ale angielski znam kiepsko. Do rzeczy...
Jakikolwiek nie byłby to klient, gdzieś musi trzymać pliki. Przeglądarki trzymają je w cache.
Nowy klient TSO trzyma je, jak mi się wydaje w takiej oto lokalizacji jako zwykłe pliki:
**C:\Users\NAME_USER\AppData\Local\Microsoft\Windows\INetCache\IE\...**
Podmieniłem grafiki kolekcji na inne ale po restarcie klienta ich nie widzi. Niestety moja wiedza na temat programowania nie jest duża i nie wiem, jak to zrobić programowo.

**Comment by perceptron8** [comment]
@Kshyhoo67 Tak jak wspomniałem wyżej, nie mam za bardzo możliwości obsługi klientów nie-przeglądarkowych. Pinky nie działa na zasadzie podmiany plików, ale przechwytywania żądań. Nie da się czegoś takiego zrobić w klientach nie wspierających wtyczek. Jakkolwiek rozumiem potrzebę, nie planuję wsparcia dla nowego klienta TSO. Mam nadzieję, że jest to - zgodnie z deklarajami Ubisoftu - klient tymczasowy / przejściowy, i że już wkrótce światło dzienne ujrzy aplikacja webowa. Jeśli tak się stanie, dostosuję do niej Pinky'ego, o ile będzie to możliwe.

**Comment by Kshyhoo67** [comment]
Rozumiem to i nie nalegam, dziękuję za dobrą robotę :) Ja również mam nadzieję, że Ubisoft upora się z nową aplikacją, bo jak na razie rozczarował sporo graczy systemów 32bit, jak i innych systemów operacyjnych.

**Comment by tOOmki** [comment]
Dzięki za dotychczasową robotę. 
Ja oprócz pinky używałem jeszcze skryptu, który zamieniał język niemiecki na polski.
Bo zacząłem grać na serwerze niemieckim, bo tam DSO wystartowało jako pierwsze.
Polski serwer DSO powstał chyba ponad rok później lub jeszcze później - nie miałem tyle zacięcia żeby od początku wszystko zaczynać.
Skrypt działa/ł na tempermonkey: https://userscripts-mirror.org/scripts/source/102221.user.js

Może gdy przejdą na Unity pod przeglądarkę to pomógłbyś mi z dostosowaniem tego skryptu, o ile się da.

**Comment by perceptron8** [comment]
@tOOmki Wiesz o https://github.com/perceptron8/babel.ext, prawda? ;) Teraz już pewnie nie skorzystasz, ale do niedawna działało całkiem dobrze. Przydawało się na testowym. Gdy przejdą na Unity pod przeglądarkę, zaktualizuję.

**Comment by tOOmki** [comment]
Od początku korzystałem z tego skryptu co podałem i wszystko działało. 
Raz była jakaś akcja że przestało i potem nagle samo wróciło. 
Ale wielki dzięki za info.

**Comment by Krydolph** [comment]
Damn! I had really hoped you were ready with a magic fix :D Maybe a config file that needed some changing or something. 
Well... We just have to live without, I hope you can make something for the unity version when that comes out. Your work are greatly appreciated by a lot of people and used every day! 
Keep up the good work!

**Comment by fiddinky** [comment]
An alternative for Pinky ist fiddler. Here is a TSO-related tutorial in german, may be in a short time in english to.

https://fiddinky.mystrikingly.com/

Thanks for all the work at pinky, I hope it will work on the UNity-client again in a near future.

**Comment by Krydolph** [comment]
> An alternative for Pinky ist fiddler. Here is a TSO-related tutorial in german, may be in a short time in english too.
> 
> https://fiddinky.mystrikingly.com/
> 
> Thanks for all the work at pinky, I hope it will work on the UNity-client again in a near future.

tyvm! I just tried this out.... Its a bit more work, but very well explained (google translate helped with the german part) 
And it works like a charm so far.

**Comment by criss20ster** [comment]
And someone knows why my connection to the browser is blocked

**Comment by Algernoon123** [comment]
thanks fiddinky ! Looks great ! ( not tested yet)

**Comment by janrenzlow** [comment]
Hallo fiddinky,
danke für Deine super Anleitung ud den fertigen Konfigurationsdateien. Funktioniert hervorragend. Ist aber dirty und nurmit entsprechendem Sachverstand zu nutzen. Auf keinen Fall was für DAUs oder Firmenrechner ^^

**Comment by fiddinky** [comment]
> 
> 
> Hallo fiddinky,
> danke für Deine super Anleitung ud den fertigen Konfigurationsdateien. Funktioniert hervorragend. Ist aber dirty und nurmit entsprechendem Sachverstand zu nutzen. Auf keinen Fall was für DAUs oder Firmenrechner ^^

Wenn man Fiddler auf einem Firmenrechner installieren kann, dann sollte der Admin gefeuert werden :-) Jupp, es ist dirty, aber da es eine reiner HTTP Proxy im Userspace ist, ist es meines Erachtens nicht gefährlicher als Flash.

**Comment by janrenzlow** [comment]
> > Hallo fiddinky,
> > danke für Deine super Anleitung ud den fertigen Konfigurationsdateien. Funktioniert hervorragend. Ist aber dirty und nurmit entsprechendem Sachverstand zu nutzen. Auf keinen Fall was für DAUs oder Firmenrechner ^^
> 
> Wenn man Fiddler als unprivilegierter User auf einem Firmenrechner installieren kann, dann sollte der Admin gefeuert werden :-) Jupp, es ist dirty, aber da es eine reiner HTTP Proxy im Userspace ist, ist es meines Erachtens nicht gefährlicher als Flash.

Tauscht auch Sammelchen in ATs. Vom Erscheinungsbild nicht von PINKY zu unterscheiden. Funktioniert auch mit vorausgeschalteter VPN (hier: cyberghost). Respekt

**Comment by eleanora1963** [comment]
please where is the tools folder to find the https as have no clue how to do this thankyou have tried to find but no luck

**Comment by TGHarosch** [comment]
Vielen dank für das Fiddinky Ding, 

1. Kannst du auf der Homepage eine Kommentarfunktion einbauen dann kann man dich dort direkt erreichen ? 
2. kannst du anstelle des pinken Monsters nicht einen Maus-klick einbauen ? 
3. Wenn du punkt 2 nicht umsetzten möchtest weil es dir zu sehr ins spiel eingreift, kannst du mir sagen wie ich das mache ? *G*
TOP arbeit.

**Comment by fiddinky** [comment]
Hi,

Ein Kontakt-Formular gibts jetzt. Kommentar gibts bei dieser Webseite leider nicht, dafür ist sie schön anonym, wir wollen ja weiter spielen:-) bitte nutzt es ab sofort, damit Pinky hier im Frühjahr durchstarten kann und nicht hunderte Beiträge zu fiddinky rumhängen hat.
Und fiddinky kann die Sammlis nicht automatisch anklicken, es tauscht einfach nur die Grafiken im Spiel aus, genauso wie pinky. Leider no way.
------
Hi,

A contact form is now available. Unfortunately, there are no comments on this website, but it is anonymous, because we want to keep playing :-) Please use it from now on, so that pinky can start here in spring and doesn't have hundreds of contributions to fiddinky hanging around.
And fiddinky can't click the collectibles automatically, it just swaps the graphics in the game, just like pinky. Unfortunately no way.

Translated with www.DeepL.com/Translator (free version)


> Vielen dank für das Fiddinky Ding,
> 
>     1. Kannst du auf der Homepage eine Kommentarfunktion einbauen dann kann man dich dort direkt erreichen ?
>     2. kannst du anstelle des pinken Monsters nicht einen Maus-klick einbauen ?
>     3. Wenn du punkt 2 nicht umsetzten möchtest weil es dir zu sehr ins spiel eingreift, kannst du mir sagen wie ich das mache ?

**Comment by adamlis** [comment]
PL

Jeżeli ktoś nie jest fanem instalowania proxy przechwytującego ruch, to przygotowałem instrukcję krok-po-kroku jak podmienić grafiki w cache. Obecnie wrzuciłem statycznie 11 grafik (8 z mapy podstawowej i 3 z eventu swiatecznego tez mapy podstawowej). Ponieważ wyszło mi, że podmiana pliku cache możliwa jest tylko na plik o identycznym rozmiarze w bajtach, to napisałem sobie generator grafik o odpowiednim rozmiarze - ale na razie go nie udostępniłem ponieważ kod jest paskudny.

Ogólnie jest to dosyć żmudne, szczególnie jak cache wyekspiruje i się pojawiają nowe pliki w nowych podkatalogach. Ale jest pole do oskryptowania tego - ja się nie podejmuję - ogólnie jakby to się dało zrobić w narzędziach POSIX to spoko: to jest find na katalog, sprawdzenie sum kontrolnych znanych plików (albo po nazwach) i podmiana na właściwe. No ale nie pracuję na co dzień w środowisku Windows, żebym się czuł w tym dobrze, a głupio skasować komuś np. pół dysku :D

Instrukcja jak to podmieniać manualnie jest (tylko po polsku) pod tym adresem: dropbox.com/sh/cv1hyta37vt9edf/AABuA7NYtexIt8ao4Q1OWL0za?dl=0 - zaś oskryptowanie tego w windows pewnie najlepiej byłoby zrobić toolem z okienkiem i przyciskami "podmień".

EN

For those who do not feel comfortable with running traffic intercepting proxy on workstation, I've prepared step-by-step explanation on manually replacing PNG files of collectibles in Windows cache. It's available however only in Polish. Since due to my best knowledge on-disk replaced cache entry must have same byte-size, I've written ugly Python script that is capable of generating same byte-sized (and also same pixel-sized) mono-color rectangle in PNG based on given file. However I've not yet shared this script since it's really ugly. I've applied this for 8 collectibles on home island and 3 additional ones from x-mas event - and placed them in ZIP together with step-by-step explanation.

In general, manual handling file replacement in cache is time consuming and can be really irritating especially when cache entries expires and file names are slightly changes. However there is an area to script this - if this could be done in POSIX style then it would not be any problem - just find files based on hash or filename and replace them. For me it is not an option as I'm even not Windows user on daily basis - and I do not feel strong enough to write script for replacing arbitrary files - what if my script would replace half of user's files on whole drive?

Anyway - tutorial on manual file replacement (only in Polish) is in the following location: dropbox.com/sh/cv1hyta37vt9edf/AABuA7NYtexIt8ao4Q1OWL0za?dl=0 - and regarding scripting this, for me option to write small windows app with big button "replace" would work best (however it might be that app would need a collection of .NET libs taking 5GB of disk space)

**Comment by januzi** [comment]
> Może gdy przejdą na Unity pod przeglądarkę to pomógłbyś mi z dostosowaniem tego skryptu, o ile się da.

Potrafisz skompilować program napisany w c++? Jeśli tak, to mogę wrzucić kod aplikacji, która podmienia znaczniki języka przy odpalaniu nowego klienta.

**Comment by tOOmki** [comment]
Za słaby jestem :[

**Comment by januzi** [comment]
@tOOmki 
https://github.com/januzi/settlers_lang_changer
poradzisz sobie z wgraniem i wybraniem jako domyślna aplikacja?

**Comment by tOOmki** [comment]
> @tOOmki
> https://github.com/januzi/settlers_lang_changer
> poradzisz sobie z wgraniem i wybraniem jako domyślna aplikacja?

Działa, dzięki

**Comment by janrenzlow** [comment]
DE:  Hallo adamlis,  
vielen Dank für Deine Erklärung. Ich habe die Erklärung verstanden, obwohl ich kein Polnisch kann. Du hast nur die Bilder der Standardsammelgegenstände und die Weihnachtsgegenstände umgewandelt. Es fehlen noch die speziellen Sammelgegenstände aus den Abenteuer. Wo kann ich das Python-Skript bekommen, dass die Grafiken umwandelt. 
Vielen Dank Jan

PL: Witam adamlis, 
bardzo dziękuję za wyjaśnienie. Zrozumiałem wyjaśnienie, chociaż nie mówię po polsku. Przekonwertowałeś tylko obrazy standardowych przedmiotów kolekcjonerskich i świątecznych. Wciąż brakuje specjalnych przedmiotów kolekcjonerskich z przygód. Gdzie mogę znaleźć skrypt w języku Python, który konwertuje grafikę. 
Dziękuję Jan

EN: Hello adamlis, 
thank you very much for your explanation. I understood the explanation even though I don't speak Polish. You only converted the images of the standard collectibles and the Christmas items. The special collectibles from the adventures are still missing. Where can I get the python script that converts the graphics. 
Thank you Jan

**Comment by perceptron8** [comment]
@januzi @tOOmki https://github.com/perceptron8/babel.ext/ został zaktualizowany, dzięki czemu obsługuje przejściowego klienta TSO. Instalacja tradycyjnie wymaga 2-3 kliknięć - bez kompilacji / ściągania aplikacji czy modyfikacji rejestru. Jeśli możecie, dajcie znać, czy rozszerzenie działa tak, jak powinno.

---

https://github.com/perceptron8/babel.ext/ has been updated to support transitional client. You can install it, as always in case of extensions, with 2-3 clicks - there's no need to compile, download or edit windows registry. Please, if you can, let me know, whether everything works as expected.

**Comment by caheuer** [comment]
I have tinkered together a python program that works with the transitional client. It is pretty unstable, though. It works by editing the hosts file on Windows and emulating a web server locally. Maybe it might for you as well.

https://github.com/caheuer/tso-collectible-finder

**Comment by janzbik** [comment]
it used to work (kiedyś to działało)
https://rapidu.net/9689646128/TSO_Tools-v47.rar

**Comment by Kshyhoo67** [comment]
> it used to work (kiedyś to działało)
> https://rapidu.net/9689646128/TSO_Tools-v47.rar

404 - File not found
Ten projekt upadł rok temu.

**Comment by janzbik** [comment]
Działało jeszcze niedawno (kolekcje oraz wysyłanie poszukiwaczy.

**Comment by Bruno-Lochet** [comment]
> An alternative for Pinky ist fiddler. Here is a TSO-related tutorial in german and in english.
> https://fiddinky.mystrikingly.com/
> 
> Thanks for all the work at pinky, I hope it will work on the UNity-client again in a near future.

Yes, Perceptron, thanks for the work.
I also made a manual to adapt Fiddler and have the same behavior as Pinky.
[https://github.com/Bruno-Lochet/Pinky-Fiddler]

Mine is more complete that "fiddinky" but, I shall admit, "fiddinky" is more user friendly.

**Comment by perceptron8** [comment]
It's very likely that Unity version will soon be supported. See #74.
